---
format: pdf
editor: visual
---

+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
| Year    | Question | Related field                       | Time spend | Turn out                                                                        |
+=========+==========+=====================================+============+=================================================================================+
| 2021-T  | 1a-c     | 1.  pdf, cdf                        | short      | good                                                                            |
|         |          |                                     |            |                                                                                 |
|         |          | 2.  E, Var                          |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 1 d-f    | 1.  \[Asymptotic Probability\]      | long       | don't know how to come up with the thing                                        |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2        | 1.  Conditional Probability         | 3h         | Can't do Binormal pdf, Expectation and variance                                 |
|         |          |                                     |            |                                                                                 |
|         |          | 2.  \[Multivariate Transformation\] |            | Can't do conditional expectation                                                |
|         |          |                                     |            |                                                                                 |
|         |          | 3.  \[Binormal Distribution\]       |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3a       | Transformation                      | short      | good                                                                            |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3b       | 1.  Order Statistics                | Long       | didn't finish                                                                   |
|         |          |                                     |            |                                                                                 |
|         |          | 2.                                  |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3c-d     | 1.  \[Hypothesis Testing\]          | Long       | Didn't finish                                                                   |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4a-d     | -   CLT                             |            |                                                                                 |
|         |          |                                     |            |                                                                                 |
|         |          | -   Delta                           |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4e       | -   Converge                        |            | Can't do it                                                                     |
|         |          |                                     |            |                                                                                 |
|         |          | -   Taylor Series                   |            | Very easy if you think of second order Delta                                    |
|         |          |                                     |            |                                                                                 |
|         |          | -   Second Order Delta              |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 5a-c     | -   MOM                             | Long       | Fisher info can only applied to exponential family                              |
|         |          |                                     |            |                                                                                 |
|         |          | -   UMVUE                           |            | CRLB only apply for family distribution that support doesn't depend on paramter |
|         |          |                                     |            |                                                                                 |
|         |          | -   Rao-blackwell                   |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 5d-f     | -   Bayesian                        |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 6        | -   Gal-Markov                      |            | Don't know how to get the order statistics distribution                         |
|         |          |                                     |            |                                                                                 |
|         |          | -   lagrange multiplier             |            |                                                                                 |
|         |          |                                     |            |                                                                                 |
|         |          | -   Order Statsitics                |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
| 2021-A  |          |                                     |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
| 2022-A  | 1c       | \[T-test\]                          | Long       | Didn't Finish, still don't understand equal variance vs. unequal variance       |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 1g       | \[T-test\]                          | Long       | Also don't understand the assumption to get a exact t-test, approx. t-test.     |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2        | 1.  Log-transform                   | medium     | Not familiar with log transform value intepretation                             |
|         |          |                                     |            |                                                                                 |
|         |          | 2.  Logistic                        |            | Not familiar with the idea of Risk and Odd                                      |
|         |          |                                     |            |                                                                                 |
|         |          |                                     |            | Not familiar with Logisitcs                                                     |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3a       | Saturated                           | Long       | Don't understand how a model can be saturated                                   |
|         |          |                                     |            |                                                                                 |
|         |          |                                     |            | Don't understand how constrains works on the saturated                          |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3b       | 1.  logistic                        | Long       | Not familiar with the forms of the model                                        |
|         |          |                                     |            |                                                                                 |
|         |          | 2.  Multiordinal                    |            | Don't know the proportional odd assumption                                      |
|         |          |                                     |            |                                                                                 |
|         |          | 3.  Log-odd                         |            | Don't know how to hand calculated logistic model                                |
|         |          |                                     |            |                                                                                 |
|         |          |                                     |            | Don't know how to hand calcualted Log-odd Model                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4        | Baysian                             | Okayish    | I don't know                                                                    |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 5        | 1.  Simulation                      | Okayish    | Not sure how to evaluate CI performance                                         |
|         |          |                                     |            |                                                                                 |
|         |          | 2.  Bootstrap CI                    |            | Not sure how boostrap CI                                                        |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 6        | -   Non-linear model                | Long       | Not familiar with multivariate delta Methods                                    |
|         |          |                                     |            |                                                                                 |
|         |          | -   Delta method                    |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
| 2022-T  | 1b       | -   Geometric                       |            | Don't know the MGF of Geometric                                                 |
|         |          |                                     |            |                                                                                 |
|         |          | -   MGF                             |            | Don't know the trick to find MGF                                                |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 1j       | AUC                                 |            | Don't understand the upper bound of AUC                                         |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2c       |                                     |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2d       | Transformation                      |            | Transformation with Jacobian apply to pdf                                       |
|         |          |                                     |            |                                                                                 |
|         |          |                                     |            | Non-independent b/c of Indicator function                                       |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2g       | -   Slusky                          |            | good, but worth reviewing                                                       |
|         |          |                                     |            |                                                                                 |
|         |          | -   LLN                             |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 2h       | -   CLT                             |            | Confused at which variance should use in delta method                           |
|         |          |                                     |            |                                                                                 |
|         |          | -   Delta Method                    |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3c       | -   UMVE                            |            | Completely forget about Lehmann-scheffe                                         |
|         |          |                                     |            |                                                                                 |
|         |          | -   Complete                        |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3d       |                                     |            | Don't know how to prove                                                         |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 3e       |                                     |            | Completely no idea                                                              |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4a-b     | -   MGF                             |            | Bad, not thinking of MGF and got stuck                                          |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4c       | Method of Moment                    |            | Still don't know how to get a MOM estimator                                     |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 4d       | Asymptotic Distribution             |            | How to determine asymptotic distribution? converge in distribution?             |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 5        |                                     |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 6a       | MLE                                 | fast       | Like bob's                                                                      |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 6b-c     | bayesian                            |            |                                                                                 |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+
|         | 6d-f     | Unbiased                            | Bad        | F                                                                               |
+---------+----------+-------------------------------------+------------+---------------------------------------------------------------------------------+

: Comps Practice
